### ISSUE TITLE
Android 14调用register时报错

### ISSUE THREAD

**Issue by NEOLEE98** [andfaraway/flutter_wxwork#11]
Unhandled Exception: PlatformException(error, com.app: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts

**Comment by NEOLEE98** [comment]
```
2024-09-25 18:21:10.483 19999-19999 MethodChan...ter_wxwork com.hygj.hygj_oa                     E  Failed to handle method call
                                                                                                    java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
2024-09-25 18:21:10.486 19999-20014 flutter                 com.hygj.hygj_oa                     E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
                                                                                                    
                                                                                                    )
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      FlutterWxwork.register (package:flutter_wxwork/flutter_wxwork.dart:13:22)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      _LoginPageState._initWorkWxPlugin (package:hygj_oa/pages/login_page.dart:40:25)
                                                                                                    <asynchronous suspension>
2024-09-25 18:23:16.077 23789-24413 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(429)] value vivo
2024-09-25 18:23:16.077 23789-24413 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(431)] fontXmlName /data/user/0/com.tencent.mm/code_cache/com.tencent.mm:appbrand0/flutter_custom_fonts2.xml
2024-09-25 18:23:16.077 23789-24413 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(583)] use default font mgr
2024-09-25 18:23:16.078 23789-24412 flutter                 com.tencent.mm                       I  [INFO:flutter_main.cc(212)] set slow runner report callback
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop_android.cc(22)] prepare main_looper: 1
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(109)] start create platform thread message loop
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop_android.cc(49)] AcquireLooperForMainThread success
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(111)] create platform thread message loop end
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(116)] start AttachLoopToPlatformThread
2024-09-25 18:23:16.092 23789-23789 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(118)] AttachLoopToPlatformThread reset tls_message_loop. g_platform_thread_loop:0x7d64c31530 tls_message_loop:0x0
2024-09-25 18:23:16.095 23789-24416 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(32)] create MessageLoop for current thread
2024-09-25 18:23:38.446 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.EmojiPlatformResPathProvider]: configInit
2024-09-25 18:23:38.446 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.SystemEmojiProcessor]: try to init system emoji res , path:/data/user/0/com.tencent.mm/app_font/color_emoji_new
2024-09-25 18:23:38.448 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.SystemEmojiProcessor]: check , read emoji headerinfo bytes count:16
2024-09-25 18:23:38.448 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.SystemEmojiProcessor]: supportVersion:1,emojiVersion:1647833108401000, headerSize:119152
2024-09-25 18:23:38.470 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.SystemEmojiProcessor]: emojiheader parse done, emoji item count:4084 , softbankItem count:470, nameIdxItem count:467
2024-09-25 18:23:38.504 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.QQSmileyManager]: initXMLSmiley texts.length:105 _textsCh.length:105
2024-09-25 18:23:38.505 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.QQSmileyManager]: initXMLSmiley success
2024-09-25 18:23:38.507 29875-25104 flutter                 com.tencent.mm                       I  [I][MicroMsg.Flutter.Emoji.QQSmileyManager]: updateSmiley: new smiley load size: 45
2024-09-25 18:25:35.685 28253-29071 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(429)] value vivo
2024-09-25 18:25:35.693 28253-29071 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(431)] fontXmlName /data/user/0/com.tencent.mm/code_cache/com.tencent.mm:appbrand0/flutter_custom_fonts2.xml
2024-09-25 18:25:35.693 28253-29071 flutter                 com.tencent.mm                       E  [ERROR:flutter/lib/ui/text/fontmgr_default_android.cc(583)] use default font mgr
2024-09-25 18:25:35.695 28253-29070 flutter                 com.tencent.mm                       I  [INFO:flutter_main.cc(212)] set slow runner report callback
2024-09-25 18:25:35.718 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop_android.cc(22)] prepare main_looper: 1
2024-09-25 18:25:35.719 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(109)] start create platform thread message loop
2024-09-25 18:25:35.719 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop_android.cc(49)] AcquireLooperForMainThread success
2024-09-25 18:25:35.719 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(111)] create platform thread message loop end
2024-09-25 18:25:35.719 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(116)] start AttachLoopToPlatformThread
2024-09-25 18:25:35.719 28253-28253 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(118)] AttachLoopToPlatformThread reset tls_message_loop. g_platform_thread_loop:0x7d64c32d10 tls_message_loop:0x0
2024-09-25 18:25:35.728 28253-29073 flutter                 com.tencent.mm                       I  [INFO:message_loop.cc(32)] create MessageLoop for current thread
2024-09-25 18:29:09.062 19999-19999 MethodChan...ter_wxwork com.hygj.hygj_oa                     E  Failed to handle method call
                                                                                                    java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
2024-09-25 18:29:09.065 19999-20014 flutter                 com.hygj.hygj_oa                     E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
                                                                                                    
                                                                                                    )
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      FlutterWxwork.register (package:flutter_wxwork/flutter_wxwork.dart:13:22)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      _LoginPageState._initWorkWxPlugin (package:hygj_oa/pages/login_page.dart:40:25)
                                                                                                    <asynchronous suspension>
2024-09-25 18:38:47.710 18078-5418  ResourceExtractor       com.hygj.hygj_oa                     I  Extracted baseline resource assets/flutter_assets/kernel_blob.bin
2024-09-25 18:38:47.710 18078-5418  ResourceExtractor       com.hygj.hygj_oa                     I  Extracted baseline resource assets/flutter_assets/vm_snapshot_data
2024-09-25 18:38:47.747 18078-5418  ResourceExtractor       com.hygj.hygj_oa                     I  Extracted baseline resource assets/flutter_assets/isolate_snapshot_data
2024-09-25 18:38:47.863 18078-5495  flutter                 com.hygj.hygj_oa                     I  The Dart VM service is listening on http://127.0.0.1:36799/95g3ebd1xA0=/
2024-09-25 18:38:49.750 18078-18078 MethodChan...ter_wxwork com.hygj.hygj_oa                     E  Failed to handle method call
                                                                                                    java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
2024-09-25 18:38:49.757 18078-5464  flutter                 com.hygj.hygj_oa                     E  [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: PlatformException(error, com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts, null, java.lang.SecurityException: com.hygj.hygj_oa: One of RECEIVER_EXPORTED or RECEIVER_NOT_EXPORTED should be specified when a receiver isn't being registered exclusively for system broadcasts
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3071)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3055)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3038)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2980)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.registerReceiverWithFeature(IActivityManager.java:6427)
                                                                                                    	at android.app.ContextImpl.registerReceiverInternal(ContextImpl.java:1876)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1811)
                                                                                                    	at android.app.ContextImpl.registerReceiver(ContextImpl.java:1799)
                                                                                                    	at android.content.ContextWrapper.registerReceiver(ContextWrapper.java:755)
                                                                                                    	at com.tencent.wework.api.WWAPIImpl.registerApp(WWAPIImpl.java:110)
                                                                                                    	at com.example.flutter_wxwork.FlutterWxworkPlugin.onMethodCall(FlutterWxworkPlugin.java:74)
                                                                                                    	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:267)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.invokeHandler(DartMessenger.java:292)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger.lambda$dispatchMessageToQueue$0$io-flutter-embedding-engine-dart-DartMessenger(DartMessenger.java:319)
                                                                                                    	at io.flutter.embedding.engine.dart.DartMessenger$$ExternalSyntheticLambda0.run(Unknown Source:12)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:1013)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:101)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:226)
                                                                                                    	at android.os.Looper.loop(Looper.java:328)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:9233)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:594)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActivityManagerService.registerReceiverWithFeature(ActivityManagerService.java:15737)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$registerReceiverWithFeature$(IActivityManager.java:12545)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3160)
                                                                                                    	at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:3229)
                                                                                                    	at android.os.Binder.execTransactInternal(Binder.java:1405)
                                                                                                    
                                                                                                    )
                                                                                                    #0      StandardMethodCodec.decodeEnvelope (package:flutter/src/services/message_codecs.dart:648:7)
                                                                                                    #1      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:334:18)
                                                                                                    <asynchronous suspension>
                                                                                                    #2      FlutterWxwork.register (package:flutter_wxwork/flutter_wxwork.dart:13:22)
                                                                                                    <asynchronous suspension>
                                                                                                    #3      _LoginPageState._initWorkWxPlugin (package:hygj_oa/pages/login_page.dart:40:25)
                                                                                                    <asynchronous suspension>
```

**Comment by andfaraway** [comment]
@NEOLEE98 尝试降低targetSdk看下

**Comment by andfaraway** [comment]
这是腾讯sdk的bug,目前还没有更新解决,临时处理办法就是降低targetSdk,等后续官方更新后跟进

**Comment by NEOLEE98** [comment]
实测降低targetSDK可以解决，之前是flutter默认的
